name: Deploy to Production

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Check for TypeScript errors
        run: npx tsc --noEmit
        
      - name: Lint
        run: npm run lint
        
      - name: Build
        run: npm run build

      - name: Backup current deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/skit.sascha-kohler.at
            if [ -d "current" ]; then
              rm -rf backup
              mv current backup
            fi
            mkdir -p current

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/skit.sascha-kohler.at/current"
          strip_components: 1
          overwrite: true

      - name: Post-deployment configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/skit.sascha-kohler.at/current
            sudo chmod -R 755 /var/www/skit.sascha-kohler.at/current
            
      - name: Verify deployment
        run: |
          if curl -s --head https://skit.sascha-kohler.at | grep "200 OK" > /dev/null; then 
            echo "Deployment successful!"
          else
            echo "Deployment verification failed"
            exit 1
          fi

      - name: Notification
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { context } = require('@actions/github');
            const status = context.job.status === 'success' ? '✅' : '❌';
            const message = `Production Deployment ${context.job.status}: ${status}\nCommit: ${context.sha}`;
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: message
            });
