name: Deploy Maintenance

on:
  push:
    branches: [maintenance]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
        
      - name: Backup production config
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Backup nginx production config wenn noch nicht vorhanden
            if [ ! -f /etc/nginx/sites-available/skit.sascha-kohler.at.conf.production ]; then
              sudo cp /etc/nginx/sites-available/skit.sascha-kohler.at.conf /etc/nginx/sites-available/skit.sascha-kohler.at.conf.production
            fi

      - name: Deploy Maintenance Page
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/skit.sascha-kohler.at/maintenance"
          strip_components: 1
          overwrite: true

      - name: Configure Maintenance Mode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Setze Berechtigungen
            sudo chown -R www-data:www-data /var/www/skit.sascha-kohler.at/maintenance
            sudo chmod -R 755 /var/www/skit.sascha-kohler.at/maintenance
            
            # Aktiviere Maintenance-Konfiguration
            sudo cp /etc/nginx/sites-available/skit.sascha-kohler.at.maintenance.conf /etc/nginx/sites-available/skit.sascha-kohler.at.conf
            
            # Teste und lade Nginx neu
            sudo nginx -t
            if [ $? -eq 0 ]; then
                sudo systemctl reload nginx
            else
                echo "Nginx configuration test failed"
                exit 1
            fi
            
      - name: Verify Maintenance Mode
        run: |
          sleep 5
          if curl -s --head https://skit.sascha-kohler.at | grep "503" > /dev/null; then 
            echo "Maintenance mode activated successfully!"
          else
            echo "Maintenance mode activation failed"
            exit 1
          fi